### ISSUE TITLE
Installation Documentation Could be Improved

### ISSUE THREAD

**Issue by AT-StephenDetomasi** [ponceto/pve-autosnap#3]
Hi there. I noticed that the documentation for installing PVE autosnap on Proxmox is a bit more complicated than it needs to be. Is there any chance of updating it with a permalink as well, so that the same script can be used to install the latest version? Below is what I ended up creating for myself, but it'll only work for the current version at the time of writing.

`apt install make && wget -O /tmp/autosnap_amd64.deb https://github.com/ponceto/pve-autosnap/releases/download/v1.4.1/pve-autosnap_1.4.1-1_amd64.deb && apt install /tmp/autosnap_amd64.deb`

**Comment by ponceto** [comment]
Hi!

Thank you for the feedback.

I'll not add such a permalink, because I use GitHub, GitLab or Bitbucket as multiples mirrors of my personal GitLab CE software factory.

That's not the usual way on any forge to fetch the last version and this is not really a feature for the project, but a facility which is not directly offered by GitHub, or GitLab or Bitbucket.

But in fact you can go on the latest version with this link:

https://github.com/ponceto/pve-autosnap/releases/latest

You'll be redirected to the last version, as any GitHub project.

But I plan to deploy in the future a Debian repository to facilitate deployments and upgrades, stay tuned!

**Comment by AT-StephenDetomasi** [comment]
All good - I also want to mention that downloading to the default root folder has issues with apt, hence why I also added a small section there to download to /tmp/ with a fixed name so it can be easily installed without modifying the command.

**Comment by ponceto** [comment]
Yes. For security concerns, apt emit a warning when you're installing from root home directory at the end of the process.

**Comment by ponceto** [comment]
Documentation updated. Thank you.
